const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const defaultServices=[
 {id:crypto.randomUUID(),name:'Brake Repair',category:'Brakes',desc:'Brake inspections, pad replacement, rotors and more.',price:159.99,icon:'🛑'},
 {id:crypto.randomUUID(),name:'Oil Change',category:'Maintenance',desc:'Full-service oil changes to keep your engine running strong.',price:39.99,icon:'🛢️'},
 {id:crypto.randomUUID(),name:'Diagnostics',category:'Diagnostics',desc:'Advanced diagnostics to find the problem fast.',price:89.99,icon:'⚙️'},
 {id:crypto.randomUUID(),name:'Tires & Alignment',category:'Tires',desc:'New tires, rotations, balances, and wheel alignments.',price:89.99,icon:'🛞'},
 {id:crypto.randomUUID(),name:'A/C Service',category:'A/C Service',desc:'AC repair, recharge, and system maintenance.',price:99.99,icon:'❄️'},
 {id:crypto.randomUUID(),name:'Engine Repair',category:'Engine Repair',desc:'From minor fixes to major engine repair, we do it all.',price:249.99,icon:'🔧'}];
let services=JSON.parse(localStorage.getItem('rta_services')||'null')||defaultServices;let pos=JSON.parse(localStorage.getItem('rta_pos')||'[]');let editing=null;let lines=[];
function save(){localStorage.setItem('rta_services',JSON.stringify(services));localStorage.setItem('rta_pos',JSON.stringify(pos));}
function money(n){return '$'+Number(n||0).toFixed(2)}
function renderPublic(){ $('#publicServices').innerHTML=services.slice(0,6).map(s=>`<article class="service-card"><div class="icon">${s.icon||'🔧'}</div><h3>${s.name}</h3><p>${s.desc}</p><p class="price">Starting at ${money(s.price)}</p></article>`).join('');}
function renderServices(){ $('#servicesTable').innerHTML=services.map(s=>`<tr><td>${s.name}</td><td>${s.category}</td><td>${s.desc}</td><td>${money(s.price)}</td><td class="actions"><button onclick="editSvc('${s.id}')">✏️</button><button onclick="delSvc('${s.id}')">🗑️</button></td></tr>`).join(''); $('#lineService').innerHTML=services.map(s=>`<option value="${s.id}">${s.name} - ${money(s.price)}</option>`).join(''); $('#serviceCount').textContent=services.length;}
function renderDashboard(){ $('#poCount').textContent=pos.length; $('#revenueCount').textContent=money(pos.reduce((a,p)=>a+p.total,0)); $('#recentPOs').innerHTML=pos.slice(-5).reverse().map(p=>`<div class="history-row"><b>${p.number}</b><span>${p.vendor}</span><span>${money(p.total)}</span></div>`).join('')||'<p>No purchase orders yet.</p>';}
function renderLines(){ $('#lineItems').innerHTML=lines.map((l,i)=>`<div class="line"><span>${l.name}</span><span>${l.qty}</span><span>${money(l.price*l.qty)}</span><button onclick="removeLine(${i})">×</button></div>`).join(''); renderPreview();}
function renderPreview(){const sub=lines.reduce((a,l)=>a+l.price*l.qty,0),tax=sub*(Number($('#taxRate').value||0)/100),total=sub+tax;$('#poPreview').innerHTML=`<div class="po-doc"><div class="po-head"><div><h1>ROGERS</h1><b>TIRE & AUTO</b><p>123 Main Street<br>Greenville, SC 29601<br>(864) 555-0198</p></div><div><h2>PURCHASE ORDER</h2><p><b>PO Number:</b> ${$('#poNumber').value}<br><b>Date:</b> ${$('#poDate').value}<br><b>Vendor:</b> ${$('#poVendor').value}</p></div></div><p><b>Bill To:</b><br>${$('#poBillTo').value}</p><table><thead><tr><th>Item</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>${lines.map(l=>`<tr><td>${l.name}</td><td>${l.desc}</td><td>${l.qty}</td><td>${money(l.price)}</td><td>${money(l.price*l.qty)}</td></tr>`).join('')}</tbody></table><div class="totals"><p><b>Subtotal:</b> ${money(sub)}</p><p><b>Tax:</b> ${money(tax)}</p><h3>Total: ${money(total)}</h3></div><p style="margin-top:60px">Authorized By: ______________________________</p></div>`;}
function renderHistory(){ $('#poHistory').innerHTML=pos.slice().reverse().map(p=>`<div class="history-row"><b>${p.number}</b><span>${p.vendor}</span><span>${money(p.total)}</span></div>`).join('')||'<p>No saved POs yet.</p>';}
function totals(){const sub=lines.reduce((a,l)=>a+l.price*l.qty,0),tax=sub*(Number($('#taxRate').value||0)/100);return{sub,tax,total:sub+tax}}
window.editSvc=id=>{editing=id;const s=services.find(x=>x.id===id);$('#modalTitle').textContent='Edit Service';$('#svcName').value=s.name;$('#svcCategory').value=s.category;$('#svcDesc').value=s.desc;$('#svcPrice').value=s.price;$('#serviceModal').classList.remove('hidden')}
window.delSvc=id=>{services=services.filter(s=>s.id!==id);save();renderAll()}
window.removeLine=i=>{lines.splice(i,1);renderLines()}
function renderAll(){renderPublic();renderServices();renderDashboard();renderHistory();renderPreview()}
$('#adminOpen').onclick=()=>{$('#publicSite').classList.add('hidden');$('.site-header').classList.add('hidden');$('#adminApp').classList.remove('hidden');renderAll()};$('#publicOpen').onclick=()=>{$('#adminApp').classList.add('hidden');$('#publicSite').classList.remove('hidden');$('.site-header').classList.remove('hidden')};
$$('.admin-side button[data-tab]').forEach(b=>b.onclick=()=>{$$('.admin-side button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-tab').forEach(t=>t.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');renderAll()});
$('#addService').onclick=()=>{editing=null;$('#modalTitle').textContent='Add Service';['svcName','svcCategory','svcDesc','svcPrice'].forEach(id=>$('#'+id).value='');$('#serviceModal').classList.remove('hidden')};$('#cancelModal').onclick=()=>$('#serviceModal').classList.add('hidden');
$('#saveService').onclick=()=>{const obj={id:editing||crypto.randomUUID(),name:$('#svcName').value,category:$('#svcCategory').value,desc:$('#svcDesc').value,price:Number($('#svcPrice').value),icon:'🔧'}; if(editing) services=services.map(s=>s.id===editing?{...s,...obj}:s); else services.push(obj); $('#serviceModal').classList.add('hidden'); save(); renderAll()};
$('#addLine').onclick=()=>{const s=services.find(x=>x.id===$('#lineService').value);lines.push({...s,qty:Number($('#lineQty').value||1)});renderLines()};
['poVendor','poNumber','poDate','poBillTo','taxRate'].forEach(id=>$('#'+id).addEventListener('input',renderPreview));
$('#savePO').onclick=()=>{const t=totals();pos.push({number:$('#poNumber').value,vendor:$('#poVendor').value,date:$('#poDate').value,total:t.total,html:$('#poPreview').innerHTML});save();renderAll();alert('Purchase order saved.')};
$('#generatePDF').onclick=()=>{renderPreview();html2pdf().set({margin:.35,filename:($('#poNumber').value||'purchase-order')+'.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2},jsPDF:{unit:'in',format:'letter',orientation:'portrait'}}).from($('#poPreview')).save()};
$('#seedBtn').onclick=()=>{localStorage.removeItem('rta_services');localStorage.removeItem('rta_pos');location.reload()};
$('#poDate').value=new Date().toISOString().slice(0,10);$('#poNumber').value='PO-'+new Date().getFullYear()+'-0001';renderAll();
